// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcmvrbdmwcytcjtmsxsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jbXZyYmRtd2N5dGNqdG1zeHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0OTM4ODcsImV4cCI6MjA2MjA2OTg4N30.HBhkqA3xdQ6KlEh2CFlnL3Ld364DwtvwGQtjxAUgTk8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);